# Welcome to Jekyll
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home 4 Us
email: filipa.sag@gmail.com
description: "Home 4 Us, a melhor loja para adquirir os produtos mais originais para a sua casa ou para oferecer a alguém especial."
baseurl: "/home4us"
url: "localhost:4000"
tagline: "Porque a vida é feita de detalhes"
twitter_username:
github_username:  FilipaGo

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
